
CREATE TABLE IF NOT EXISTS "user" (
    "id"                    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "email"                 VARCHAR(320) NOT NULL,
	"hash"                  VARCHAR(320) NOT NULL,
    "createdAt"             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt"             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS "user_email" ON "user"("email");

CREATE TABLE IF NOT EXISTS "pokemon" (
    "id"                    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"ownerId"               INTEGER REFERENCES "user" ON DELETE CASCADE,
    "name"                 	VARCHAR(320) NOT NULL,
	"pokeId"                INTEGER NOT NULL
)
